{% set name = "hypre" %}
{% set version = "3.1.0" %}
{% set sha256 = "a6879ae9375d95c26afd97141d61e7a8092807333bf40cd180b385aed7351b2d" %}
{% set build = 0 %}

{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/hypre-space/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage("hypre", max_pin="x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - {{ mpi }}  # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - libblas
    - liblapack
    - {{ mpi }}
  run:
    - {{ mpi }}

test:
  commands:
    - test -f $PREFIX/include/HYPRE.h
    - test -f $PREFIX/lib/libHYPRE.dylib  # [osx]
    - test -f $PREFIX/lib/libHYPRE.so  # [linux]

about:
  home: https://www.llnl.gov/casc/hypre/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYRIGHT
  summary: high performance preconditioners for sparse linear systems
  description: |
    HYPRE is a library of high performance preconditioners and solvers featuring
    multigrid methods for the solution of large, sparse linear systems of equations
    on massively parallel computers.
  dev_url: https://github.com/hypre-space/hypre
  doc_url: https://hypre.readthedocs.io

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - matthiasdiener
