provider: {linux_aarch64: default, linux_ppc64le: default}
appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Vi/arMNGWSvo3Qqnhh2GthyCNGxJuhGxfHfc6RGI+FsQcXejU71/K+yGtwSmck4I19Oo5NJm1ZbkbB7w7ZHJGLNOvjT1llbl7T/8D9WYDnxv8t4+0arc+Haiq4VO3wDr2geIs/x9RFqCRicnVUvVEfkzimMTlEKFQzQV8tFAdC7N3epD4fgkPFFC9q7QzQNnqn+1yKFOcnmpPFOSLiGRWxLQqiPppVOKT3Qo9gttK/BDC0GimcD6RjsZ9x+1c2oSGkSAbWgUepDDICxKaezeGY3SEIC8cOu/U3Pl7D5KpN7Zm9vFmScFjPfCd0arELshvhKjN5gvEdmYV5YQJ8o02WMJE51NpsIdANHrhYJJUEVNb0i8EjJal6AIzsuupxILKUKESa9laJrvjQsyWzauQU/Of90jL/ZNYBCsjeCaOKAYA8u9rnXiR/zuiHKQGiQeao3aDlweistiQa1wQlqM/WKNh9yJ2IgmFZ2tLtaEw7yt1I65Sd1OzIplAMKmz+uUaPC6Ru4Ak6MiIysbrSlX7ICY0xtmAoOwXlGXj/zon1aRaQKOdRlfJHQAqZQWqSz3F1u50lpCiT7CNLx2+4pd8QvUIcZaLwfQKRMZ4YPyytq7HQj40lna4uThl8i+XWE8PI1wJ7f3qyT3JY9K+bTjPc8BNfPdAZ0Rw4/bNx23f68=}
